name: Sentiment Analysis with BERT

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/BERT

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Train model
      run: python src/train.py

    - name: Evaluate model
      run: python src/evaluate.py

    - name: Build Docker image
      run: docker build -t sentiment-api .
